### ISSUE TITLE
hiera resources don't process ssl locations properly

### ISSUE THREAD

**Issue by vrillusions** [voxpupuli/puppet-nginx#106]
Wanted to user hiera for the virtualhost configuration but running into an error I couldn't figure out the cause of.

This does not work:

``` yaml
nginx::nginx_vhosts:
  'MY.EXAMPLE.com':
    ipv6_enable: true
    www_root: '/srv/www/default/public/'
    ssl: true
    ssl_cert: 'puppet:///modules/local/EXAMPLE.com-wildcard-with_intermed.crt'
    ssl_key: 'puppet:///modules/local/EXAMPLE.com-wildcard.key'
```

But removing above and adding this to node def does:

``` puppet
  nginx::resource::vhost { 'MY.EXAMPLE.com':
    ensure      => present,
    ipv6_enable => true,
    www_root    => '/srv/www/default/public/',
    ssl         => true,
    ssl_cert    => 'puppet:///modules/local/EXAMPLE.com-wildcard-with_intermed.crt',
    ssl_key     => 'puppet:///modules/local/EXAMPLE.com-wildcard.key',
  }
```

The error I get (I did some linewraps instead of it being a single long line):

```
Error: Failed to apply catalog: Validation of File[/etc/nginx/MY.EXAMPLE.com.crt]
failed: You cannot specify more than one of content, source, target at 
/etc/puppet/modules/nginx/manifests/resource/vhost.pp:209
```

As all I see for that resource is a source type I'm not sure why it sees something else.  I've tried turning on debug mode on both server and client and didn't see anything useful come through.
