### ISSUE TITLE
Hiera/Problem with concat:  Target Concat_file with path of ... not found in the catalog

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-nginx#1102]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Agent 4.8.2-5 / Puppetserver 2.7.2-1puppetlabs1
- Ruby: 2.3.3
- Distribution: Agent: Debian Stretch / Server Debian Wheezy
- Module version:  puppet-nginx (v0.7.0)

## How to reproduce (e.g Puppet code you use)
```
nginx::resource::server:
  'default':
    ensure: present
    www_root: '/var/www'
    server_name:
      - 'matrix.example.com'
    ssl: true
    listen_port: '443'
    ssl_cert: '/etc/ssl/certs/ina-chat.example.com.crt'
    ssl_key: '/etc/ssl/private/ina-chat.example.com.key'
    ssl_protocols: 'TLSv1.1 TLSv1.2'
    ssl_cache: 'shared:SSL:50m'
    access_log: '/var/log/nginx/matrix.example.com.log'
    error_log: '/var/log/nginx/matrix.example.com.err info'
nginx::nginx_locations:
  '_matrix':
    location: '/_matrix'
    proxy: 'http://localhost:8008'
    server: 'default'
nginx::resource::server:
  'chat.example.com':
    use_default_location: false
    ensure: present
    www_root: '/opt/Riot/resources/webapp/'
    server_name:
      - 'chat.example.com'
    ssl: true
    listen_port: '443'
    ssl_cert: '/etc/ssl/certs/ina-chat.example.com.crt'
    ssl_key: '/etc/ssl/private/ina-chat.example.com.key'
    ssl_protocols: 'TLSv1.1 TLSv1.2'
    ssl_cache: 'shared:SSL:50m'
    access_log: '/var/log/nginx/ina-chat.example.com.log'
    error_log: '/var/log/nginx/ina-chat.example.com.err info'
```
## What are you seeing
```
Info: Loading facts
Info: Applying configuration version '1501740440'
Warning: /Stage[main]/Nginx/Nginx::Resource::Location[_matrix]/Concat::Fragment[default-500-0d3029858d1b26ea51afd562406fde65]/Concat_fragment[default-500-0d3029858d1b26ea51afd562406fde65]: Target Concat_file with path of /etc/nginx/sites-available/default.conf not found in the catalog
```
## What behaviour did you expect instead
Create to configuration files (default.conf / ina-chat.example.com.conf) with the parameters from the Hiera config.

## Any additional information you'd like to impart
Maybe the problem is concat. I wanted to upgrade the Concat module, but it seems impossible:

```
puppet module upgrade --ignore-dependencies puppetlabs-concat --version 3.0.0
Notice: Preparing to upgrade 'puppetlabs-concat' ...
Notice: Found 'puppetlabs-concat' (v2.2.0) in /opt/puppet/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not upgrade module 'puppetlabs-concat' (v2.2.0 -> v3.0.0)
  No version of 'puppetlabs-concat' can satisfy all dependencies
    Use `puppet module upgrade --ignore-dependencies` to upgrade only this module
```
Upgrade by hand doesn't work too:

```
server:[/opt/puppet/environments/production/modules]: puppet module list | grep conc
Warning: Module 'puppetlabs-concat' (v3.0.0) fails to meet some dependencies:
  'puppetlabs-apache' (v1.11.0) requires 'puppetlabs-concat' (>= 1.1.1 < 3.0.0)
  'icinga-icinga2' (v1.2.1) requires 'puppetlabs-concat' (>= 2.0.1 < 3.0.0)
  'puppetlabs-postgresql' (v4.8.0) requires 'puppetlabs-concat' (>= 1.1.0 <3.0.0)
├── puppetlabs-concat (v3.0.0)  invalid
root@ina-zabbix:[/opt/puppet/environments/production/modules]: puppet module list | grep std
Warning: Module 'puppetlabs-concat' (v3.0.0) fails to meet some dependencies:
  'puppetlabs-apache' (v1.11.0) requires 'puppetlabs-concat' (>= 1.1.1 < 3.0.0)
  'icinga-icinga2' (v1.2.1) requires 'puppetlabs-concat' (>= 2.0.1 < 3.0.0)
  'puppetlabs-postgresql' (v4.8.0) requires 'puppetlabs-concat' (>= 1.1.0 <3.0.0)
├── puppetlabs-stdlib (v4.16.0)
```

So, I'm stuck .... Do anybody have any suggestions ?

cu denny
