### ISSUE TITLE
Hiera:  Resource Statement, Nginx::Resource::Upstream[radius]: has no parameter named 'upstream_context'

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-nginx#1316]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10-1stretch 
- Ruby: 2.3.3p222
- Distribution: Debian Stretch (9.5)
- Module version: 0.16.0

## How to reproduce (e.g Puppet code you use)
```
nginx::nginx_streamhosts:
  'radius':
    ensure: 'present'
    listen_port: 1812
    listen_options: 'udp'
    proxy: 'radius'
    proxy_read_timeout: '1'
    proxy_connect_timeout: '1'
    raw_append:
      - 'error_log off;'
nginx::nginx_upstreams:
  'radius':
   upstream_context: 'stream'
    members:
      '10.0.0.1:1812'
        server: '10.0.0.1'
        port: '1812'
      '10.0.0.2:1812'
        server: '10.0.0.2'
        port: '1812'
```

## What are you seeing
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Nginx::Resource::Upstream[radius]: has no parameter named 'upstream_context' (file: /opt/puppet/environments/newmod/modules/nginx/manifests/init.pp, line: 202) on node fra-test-lbint-01.example.local`

## What behaviour did you expect instead
No errors, like in the [documentation](https://github.com/voxpupuli/puppet-nginx#a-stream-syslog-udp-proxy).
