### ISSUE TITLE
nginx::string_mappings in last tag v6.0.0

### ISSUE THREAD

**Issue by flepoutre** [voxpupuli/puppet-nginx#1604]
Hello,
In the last tag v6.0.0, I have the impression that we are obliged to declare a mappings.

For example I can't use this (hiera example) : 
```
nginx::string_mappings:
  uuid:
    ensure: present
    string: '$host'
    default: "''"
    mappings: {}
```

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Method call, max(): Wrong number of arguments need at least one
`

Could we make this possible again ?

Thanks.
