### ISSUE TITLE
main class has no autoindex implementation

### ISSUE THREAD

**Issue by bionix** [voxpupuli/puppet-nginx#229]
Hello,
the main class (init.pp) has no autoindex option for configuration. Currently I have no idea to implement the "define" in the main class, because the function create_ressources needs hash values (see https://github.com/jfryman/puppet-nginx/blob/master/manifests/init.pp#L137).

Currently I use the implementation for autoindex in the subclasses of puppet-nginx a string as a option value.
I'm looking for a solution. Any idea?

**Comment by dhoppe** [comment]
Hello, 

can you give us an example? I am not sure what you try to achieve. It is possible to configure `autoindex` in context of an `location` or `vhost`.

**Comment by wyardley** [comment]
As @dhoppe says, it is possible to set autoindex in vhost or location context. I'm going to close this one for now.

Somewhat sanitized hiera example:
```
nginx::nginx_vhosts:
  'foo.example.net':
    www_root: /var/www/
    server_name:
      - 'foo.example.net'
    autoindex: 'on'
```
