### ISSUE TITLE
cannot create location with only try_files defined

### ISSUE THREAD

**Issue by buckstr** [voxpupuli/puppet-nginx#470]
The check for creating a resource does not check to see if try_files is defined which alone could be used to create a valid location reference.

For example in wordpress if you want to forward rewrites to index.php you would need the following

    location / {
	  try_files $uri $uri/ /index.php?$args;
    }

**Comment by schkovich** [comment]
Actually you can do it using _location_custom_cfg_:
```
nginx::nginx_locations:
  try:
    location: '/'
    vhost: 'www.timesofmalta.dev'
    location_custom_cfg:
      try_files: '$uri $uri/ /index.php?$args'
```
resulting in:
```
  location / {
    try_files $uri $uri/ /index.php?$args;
  }
```
