### ISSUE TITLE
Cannot set ip_hash via Hiera

### ISSUE THREAD

**Issue by kemra102** [voxpupuli/puppet-nginx#563]
If I include the following in Hiera:

```yaml
nginx::nginx_upstreams: 
  'mycluster': 
    ensure: 'present' 
    members: [ '192.168.0.1:80', '192.168.0.2:80' ] 
    upstream_cfg_prepend:
      ip_hash: ''
```

The file that is created simply adds a blank line instead of the expected **ip_hash** line. As discussed in this Google Groups post the consensus seems to be an issue in the template: https://groups.google.com/forum/#!topic/puppet-users/tE3fRJaLU3A

I have tried this on two CentOS 6 environments with v0.0.10 & v0.2.2 of the module to the same effect.
