### ISSUE TITLE
Gzip values aren't passed incorrectly to nginx server

### ISSUE THREAD

**Issue by GosthMan** [voxpupuli/puppet-nginx#718]
Hello
I am trying to enable the gzip compresion on some of my nginx server but the conf isn't written correctly.
```yaml
---- # host.yaml
nginx::config::http_cfg_append:  
  gzip: on  
  gzip_proxied: any  
  gzip_vary: on  
  gzip_types:  
    - text/css
    - text/plain
    - text/xml
    - text/js
    - text/javascript
    - application/xml
    - application/javascript
    - application/x-javascript
    - application/xml+rss
    - text/javascript
    - application/json
    - text/x-json
    - image/x-icon   
  gzip_comp_level: 5
```
```
# nginx.conf
  gzip             true;
  gzip_comp_level  5;
  gzip_proxied     any;
  gzip_types       text/css;
  gzip_types       text/plain;
  gzip_types       text/xml;
  gzip_types       text/js;
  gzip_types       text/javascript;
  gzip_types       application/xml;
  gzip_types       application/javascript;
  gzip_types       application/x-javascript;
  gzip_types       application/xml+rss;
  gzip_types       text/javascript;
  gzip_types       application/json;
  gzip_types       text/x-json;
  gzip_types       image/x-icon;
  gzip_vary        true;
```
What do i have to do in order that nginx.conf receive the correct values

Thank you
