### ISSUE TITLE
Cannot deny access via location

### ISSUE THREAD

**Issue by Hufschmidt** [voxpupuli/puppet-nginx#741]
The following location (Deny access to .htaccess/.htpasswd files on nginx reverse proxy) does not work:

    location ~ /\.ht(access|passwd)$ {
      deny all;
    }

This location gets rejected by: **manifests/resource/location.pp:325**

    if (($www_root == undef) and ($proxy == undef) and ($location_alias == undef) and ($stub_status == undef) and ($fastcgi == undef) and ($uwsgi == undef) and ($location_custom_cfg == undef) and ($internal == false)) {
        fail('Cannot create a location reference without a www_root, proxy, location_alias, fastcgi, uwsgi, stub_status, internal, or location_custom_cfg defined')
      }

Website gets deployed and kept in sync on proxies and nginx loadbalancer via git, so removing htaccess on the loadbalancer is not a (good) solution.

**Comment by zaroth** [comment]
I was under the impression that that's what `location_custom_cfg` is for? The following works for me:

    nginx::resource::location {'htaccess block':
      location => '~ /\.ht(access|passwd)$',
      location_custom_cfg => { 'deny' => 'all' },
      vhost => 'myhost',
    }

**Comment by Hufschmidt** [comment]
well there a location_deny and location_allow setting on nginx::resource::location, so it feals kind of counter-intuitive having to resort back to using location_custom_cfg. (Which I'm currently using, since there is no other way)

This warning should either be extended to check location_deny, location_allow or removed all together and let nginx complain about invalid configurations...

**Comment by wyardley** [comment]
You're right, doesn't seem to let you create a location resource without one of those things.

```
nginx::nginx_vhosts:
  'test_80':
    www_root: '/var/www'
    ensure: present
    listen_port: 80
    server_name: 
      - localhost
    listen_options: 'default_server'
    use_default_location: false

nginx::nginx_locations:
  '~ /\.ht(access|passwd)$':
    location_deny:
      - 'all'
    location_allow:
      - '127.0.0.1'
    vhost: 'test_80'
```
I'm not sure what the ramifications would be of totally dropping the check in line 352 of `manifests/resource/location.pp`, though does seem like the workaround of putting something in location_custom_cfg, even if it's not the allow / deny conditions.
