### ISSUE TITLE
vhost_cfg_append with multiple entries having the same name (rewrite) not possible

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-nginx#807]
in my hiera node yaml file I would like to add more than one rewrite rule using vhost_cfg_append as such:

```
    vhost_cfg_append:
      rewrite: '^/caldav(.*)$ /remote.php/caldav$1 redirect'
      rewrite: '^/carddav(.*)$ /remote.php/carddav$1 redirect'
      rewrite: '^/webdav(.*)$ /remote.php/webdav$1 redirect'
```

but at the end the nginx server config file generated only includes one single rewrite rule (the last one). i think this should be changed so that all *_cfg_append can have config entries with the same name.
