### ISSUE TITLE
Do not re-order parameters in location_custom_cfg alphabetically

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-nginx#828]
I have some configuration parameters under `location_custom_cfg` which depend on a specific order to work correctly. Unfortunately the module re-orders my parameters alphabetically. Is it possible to avoid this re-ordering and just take the parameters in sequential order as I defined them? or do you see any other alternatives? My example config (taken from hiera) for this specific location is listed below.

```
nginx::nginx_locations:
 'php_files':
    priority: 503
    location: '~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/)'
    vhost: 'myvhost.com'
    ssl: true
    ssl_only: true
    location_custom_cfg:
      include: 'fastcgi_params'
      fastcgi_split_path_info: '^(.+\.php)(/.+)$'
      fastcgi_param:
        SCRIPT_FILENAME: '$document_root$fastcgi_script_name'
        PATH_INFO: '$fastcgi_path_info'
        HTTPS: 'on'
        modHeadersAvailable: 'true'
        front_controller_active: 'true'
      fastcgi_pass: 'phpfpm'
      fastcgi_intercept_errors: 'on'
      fastcgi_request_buffering: 'off'
```
