### ISSUE TITLE
Add more complex examples

### ISSUE THREAD

**Issue by c33s** [voxpupuli/puppet-nginx#872]
one thing is missing for this awesome module, a better documentation of complex examples. 

the mini examples are quite nice to get a quick overview but for easy an fast usage of this module it would be good to also have complex examples. they should be available as puppetcode and hiera examples.

having a simple `profile::nginx` i am try to get a hiera config for [symfony2][1] up and running.
```
class profile::nginx {
  class { 'nginx': }
  $vhosts = lookup('profile::nginx::vhosts', Hash)|$vhosts| { {} }
  $locations = lookup('profile::nginx::locations', Hash)|$locations| { {} }
  create_resources('nginx::resource::vhost', $vhosts)
  create_resources('nginx::resource::location', $locations)
```

```
server {
    server_name domain.tld www.domain.tld;
    root /var/www/project/web;

    location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    location ~ ^/(app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }
    location ~ ^/app\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }
    location ~ \.php$ {
      return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
```
the following hiera config is currently not working, i get a `Duplicate declaration: Concat::Fragment[example.com-...` error.
i also was forced to use the `internal: true` setting on `loc1`  because of the `Cannot create a location reference without a www_root, proxy, location_alias, fastcgi, uwsgi, stub_status, internal, or location_custom_cfg defined` error.  i will post the working hiera file here in the comments as soon as i figured out (looks like i have to use `location_custom_cfg`).

```
profile::nginx::vhosts:
  'example.com':
    server_name: ['example.com','www.example.com']
    www_root: '/tmp'

profile::nginx::locations:
  loc1:
    vhost: 'example.com'
    location: '/'
    internal: true
    try_files: ['$uri', '/app.php$is_args$args']
  loc2:
    vhost: 'example.com'
    location: '~ ^/(app_dev|config)\.php(/|$)'
    fastcgi: unix:/run/php5-fpm-app.sock
    fastcgi_split_path: '^(.+\.php)(/.*)$'
    fastcgi_param:
      SCRIPT_FILENAME: $realpath_root$fastcgi_script_name
      DOCUMENT_ROOT: $realpath_root
```

[1]: https://symfony.com/doc/current/setup/web_server_configuration.html#nginx
