### ISSUE TITLE
How to use  nginx::resource::vhost:add_header ?

### ISSUE THREAD

**Issue by leponot** [voxpupuli/puppet-nginx#899]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 3.8.7
- Ruby: 
- Distribution: CentOS 6 / 7
- Module version: 4.0.0

Hi

sorry i'm a beginer  with hiera, 
how i can configure nginx::resource::vhost:add_header:

i want to add secure header but i have always this error : is not a hash

from my srv-reverse-01.xxxx.xx.yaml

nginx::nginx_vhosts:
  'xxx.xxxx.xx':
    proxy: 'xxx.xxxx.xx'
    ssl: true
    ssl_cert: /etc/pki/tls/certs/xxx.xxxx.xx.crt
    ssl_key: /etc/pki/tls/private/xxx.xxxx.xx.key
    rewrite_to_https: true
    add_header:  ??

for this value for example : 
       add_header  X-Frame-Options SAMEORIGIN

templates/vhost/vhost_header.erb
<% if @add_header -%>
  <%- @add_header.keys.sort.each do |key| -%>
  add_header              '<%= key %>' '<%= @add_header[key] %>';
  <%- end -%>
<% end -%>

many thanks

regards

**Comment by wyardley** [comment]
It's a hash: 
https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/vhost.pp#L343
So I think you'll want (untested):
```
nginx::nginx_vhosts:
  [...]
  add_header:
    X-Frame-Options: SAMEORIGIN
```
HTH. Even though the module is encouraging using hiera for data, there are a lot of improvements that could be made in terms of docs.

**Comment by leponot** [comment]
i try but always this error :

nginx::nginx_vhosts:
    [...]
    add_header:
    	X-Frame-Options: SAMEORIGIN

 Error 400 on SERVER: Invalid parameter X-Frame-Options on Nginx::Resource::Vhost

working in my site file (.pp) with :
	  ::nginx::resource::vhost {
              [...]
	      add_header=> {
	        'X-Frame-Options' => 'SAMEORIGIN',
	      }
	  }

**Comment by wyardley** [comment]
Can you wrap your yaml in a code block?
I added a yaml file with the following, and applied it:

```
lana% cat throwaway_test.yaml 
nginx::nginx_vhosts:
  'foo.example.com':
    ssl: true
    ssl_cert: /etc/pki/tls/certs/server.crt
    ssl_key: /etc/pki/tls/private/server.key
    proxy: 'http://127.0.0.1:3000'
    rewrite_to_https: true
    add_header:
      X-Foo: Bar
```
and in the generated config for foo.example.com:
```
# MANAGED BY PUPPET
server {
  listen *:80;
  server_name           foo.example.com;

  add_header              'X-Foo' 'Bar';
```
