### ISSUE TITLE
nginx::locations puts locations in wrong order

### ISSUE THREAD

**Issue by kwisatz** [voxpupuli/puppet-nginx#971]
- Puppet: 3.7.5
- Ruby: 2.1.5
- Distribution: debian
- Module version: git-master

I realize this might not necessarily belong here, but it is specifically creating problems with nginx and I have the feeling that it actually changed with my upgrade from 0.5.0 to the git-master branch.
Also, I haven't found any information in the documentation on [create_resources](https://docs.puppet.com/puppet/latest/reference/function.html#createresources) that would point to it being responsible for this behavior.

Our problem is, that nginx locations are put in the wrong order. With regex locations, order matters and in our case it puts a return 404 in front of the location it should actually match first, which makes my site 404 on all requests that should go to the main controller.

It does not seem to order by order of definition, nor alphabetically by the hash key/name. But I can't find the place where the locations are sorted.

**Comment by wyardley** [comment]
When did you clone master? There was a recent PR that just reworked the logic of locations.
CCing @xaque208 

Can you provide an example of the expected vs. actual ordering?

FWIW, this is where most of the location logic happens:
https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/location.pp
https://github.com/voxpupuli/puppet-nginx/blob/master/templates/vhost/location.erb
https://github.com/voxpupuli/puppet-nginx/tree/master/templates/vhost/locations

called from

**Comment by kwisatz** [comment]
Cloned it today, a few hours back, approx. 5.

The expected ordering would be as I have it in hiera:

```yaml
  'dev':
    ensure: present
    vhost: "%{hiera('vhost')}"
    www_root: "/var/www/%{hiera('vhost')}/current/web"
    fastcgi: phpfcgi
    location: '~ ^/(app_dev|config)\.php(/|$)'
    location_cfg_append:
      fastcgi_split_path_info: '^(.+\.php)(.*)$'
      fastcgi_param SCRIPT_FILENAME: $realpath_root$fastcgi_script_name
      fastcgi_param DOCUMENT_ROOT: $realpath_root
  'prod':
    ensure: present
    vhost: "%{hiera('vhost')}"
    www_root: "/var/www/%{hiera('vhost')}/current/web"
    fastcgi: phpfcgi
    location: '~ ^/app\.php(/|$)'
    location_cfg_append:
      fastcgi_split_path_info: '^(.+\.php)(.*)$'
      fastcgi_param SCRIPT_FILENAME: $realpath_root$fastcgi_script_name
      fastcgi_param DOCUMENT_ROOT: $realpath_root
    internal: true
  '404':
    ensure: absent
    www_root: "/var/www/%{hiera('vhost')}/current/web"
    vhost: "%{hiera('vhost')}"
    location: '~ \.php'
    location_cfg_append:
      return: '404'
```

And when applying it, we can actually see that it is the 404 location, which previously (0.5.0) was at the bottom, is now moved above the other regex locations:

```
--- /etc/nginx/sites-available/vhost.conf	2016-11-14 16:22:56.813807481 +0100
+++ /tmp/puppet-file20161114-7901-nwepnc	2016-11-14 21:02:44.348400299 +0100
@@ -1,7 +1,7 @@
 # MANAGED BY PUPPET
 server {
   listen *:80;
-  server_name           vhost www.vhost;
+  server_name           vhost;
 
   index  index.html index.htm index.php;
 
@@ -15,14 +15,6 @@
     access_log /var/log/nginx/static.log;
   }
 
  location / {
     root      /var/www/vhost/current/web;
     index     index.html index.htm index.php;
@@ -60,9 +60,13 @@
     add_header Cache-Control "public";
   }
 
+  location ~ \.php {
+    root      /var/www/cms.mde-content.com/current/web;
+    index     index.html index.htm index.php;
+    return 404;
+  }
 
   location ~ ^/(app_dev|config)\.php(/|$) {
-    root          /var/www/cms.mde-content.com/current/web;
     include       /etc/nginx/fastcgi_params;
 
     fastcgi_pass  phpfcgi;
@@ -73,7 +77,6 @@
 
   location ~ ^/app\.php(/|$) {
     internal;
-    root          /var/www/vhost/current/web;
     include       /etc/nginx/fastcgi_params;
 
     fastcgi_pass  phpfcgi;
@@ -81,10 +84,4 @@
     fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
     fastcgi_split_path_info ^(.+\.php)(.*)$;
   }
-
-  location ~ \.php {
-    root      /var/www/vhost/current/web;
-    index     index.html index.htm index.php;
-    return 404;
-  }
 }
```
